spring:
  application:
    name: account-service
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver

server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: false
    fetch-registry: false

  instance:
    preferIpAddress: true